spring.application.name=dairy

spring.config.import=file:.env[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/dairy
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver